# Generated by Django 2.1.5 on 2019-03-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangSanXuat',
            fields=[
                ('MaHangSanXuat', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_HangSanXuat')),
                ('TenHangSanXuat', models.CharField(max_length=100)),
                ('HinhURL_HSX', models.CharField(max_length=100)),
                ('BiXoa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('MaLoaiSanPham', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_Hang')),
                ('TenLoaiSanPham', models.CharField(max_length=100)),
                ('BiXoa', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSanPham', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_Xe')),
                ('TenSanPham', models.CharField(max_length=100)),
                ('HinhURL', models.CharField(max_length=100)),
                ('GiaSanPham', models.IntegerField(default=0)),
                ('SoLuongTon', models.IntegerField(default=0)),
                ('SoLuongBan', models.IntegerField(default=0)),
                ('SoLuotXem', models.IntegerField(default=0)),
                ('MoTa', models.TextField()),
                ('BiXoa', models.IntegerField(default=0)),
                ('MaHangSanXuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_HangSanXuat', to='Main_Xe.HangSanXuat')),
                ('MaLoaiSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_LoaiSanPham', to='Main_Xe.LoaiSanPham')),
            ],
        ),
    ]
