# Generated by Django 2.1.5 on 2019-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Xe', '0002_auto_20190303_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='HinhURL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
