# Generated by Django 2.1.5 on 2019-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Xe', '0003_auto_20190303_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangsanxuat',
            name='HinhURL_HSX',
            field=models.ImageField(blank=True, upload_to='Node'),
        ),
    ]
